### ISSUE TITLE
Priority queue bug when multiple elements share a priority

### ISSUE THREAD

**Issue by andrei-m** [oleiade/lane#7]
If a min priority queue contains three or more elements with the same priority, `Head()` and `Pop()` return an unexpected result. e.g.

```
package main

import (
	"fmt"
	"github.com/oleiade/lane"
)

func main() {
	queue := lane.NewPQueue(lane.MINPQ)
	queue.Push("a", 2)
	queue.Push("b", 2)
	queue.Push("c", 2) // Commenting this out leads to the correct result
	queue.Push("d", 1)
	// expect "d", get "a"
	fmt.Println(queue.Head())
}
```

"a", "b" and "c" are pushed onto the queue with the same priority (2). "d" is pushed on with a higher priority according to the min-priority queue, so I expect it to become the head. Instead, "a" is returned. The queue behaves correctly if one of the elements with priority 2 is removed.

go version go1.2.2 darwin/amd64

**Comment by oleiade** [comment]
No replies. Considering it fixed. Closing.
